# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - FLASK_REPOSITORY_URI=167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-flask
      - NGINX_REPOSITORY_URI=167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-nginx
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Building the Docker images..."
      - docker build -f dockerfile_flask-prod .
      - docker tag dockerfile_flask-prod:latest $FLASK_REPOSITORY_URI:latest
      - docker push $FLASK_REPOSITORY_URI:latest
      - docker build -f dockerfile_nginx .
      - docker tag dockerfile_nginx:latest $NGINX_REPOSITORY_URI:latest
      - docker push $NGINX_REPOSITORY_URI:latest
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - my_output_file