# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - FLASK_REPOSITORY_URI=167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-flask
      - NGINX_REPOSITORY_URI=167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-nginx
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - printenv
  build:
    commands:
      - echo "Building the Docker images..."
      - docker build -f dockerfile_flask-prod -t dockerfile_flask .
      - docker tag dockerfile_flask:latest 167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-flask:latest
      - docker push 167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-flask:latest
      - docker build -f dockerfile_nginx -t dockerfile_nginx .
      - docker tag dockerfile_nginx:latest 167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-nginx:latest
      - docker push 167857347865.dkr.ecr.ap-southeast-2.amazonaws.com/docker-cicd-nginx:latest
  post_build:
    commands:
      - echo "Build completed :)"
      