version: '3.2'
services:
  mongo:
    image: mongo:latest
      
  flask:
    build:
      context: .
      dockerfile: dockerfile_flask-dev
    volumes:
    - ./api:/app
    depends_on: 
    - mongo

  nginx:
    build:
      context: .
      dockerfile: dockerfile_nginx-dev
    volumes:
    - ./web:/data/www
    ports:
    - 8080:80
    depends_on: 
    - flask
      